# Generated by Django 4.0.3 on 2022-03-21 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='picture',
            field=models.ImageField(default='default_picture.png', upload_to=''),
        ),
    ]
