# Generated by Django 4.0.3 on 2022-03-16 11:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='0895033600', max_length=16, validators=[django.core.validators.MinLengthValidator(10)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='pin',
            field=models.IntegerField(default='0343020021', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
    ]
