# Generated by Django 4.0.3 on 2022-03-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_user_phone_number_user_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='pin',
            field=models.IntegerField(),
        ),
    ]
