# Generated by Django 4.0.3 on 2022-03-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pin',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
